apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
        # documentation for this image: https://hub.docker.com/_/wordpress/
        - image: wordpress:4
          name: wordpress
          env:
            - name: WORDPRESS_DB_PASSWORD
              # Change this - must match mysql.yaml password.
              value: popotitos42
          ports:
            - containerPort: 80
              name: wordpress
