apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: federation-apiserver
  namespace: federation
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-apiserver
      labels:
        app: federated-cluster
        module: federation-apiserver
    spec:
      containers:
      - name: apiserver
        image: gcr.io/google_containers/hyperkube-amd64:v1.3.4
        command:
          - /hyperkube
          - federation-apiserver
          - --bind-address=0.0.0.0
          - --etcd-servers=http://localhost:2379
          - --service-cluster-ip-range=10.10.0.0/24
          - --secure-port=443
          - --advertise-address=ADVERTISE_ADDRESS
          - --token-auth-file=/srv/kubernetes/known-tokens.csv
        ports:
          - containerPort: 443
            name: https
          - containerPort: 8080
            name: local
        volumeMounts:
          - name: federation-apiserver-secrets
            mountPath: /srv/kubernetes/
            readOnly: true
      - name: etcd
        image: quay.io/coreos/etcd:v2.3.3
      volumes:
        - name: federation-apiserver-secrets
          secret:
            secretName: federation-apiserver-secrets
